In [ ]:
# from gensim.models import Word2Vec
# from sklearn.decomposition import PCA
# from matplotlib import pyplot
# # define training data
# sentences = [['this', 'is', 'the', 'first', 'sentence', 'for', 'word2vec'],
#             ['this', 'is', 'the', 'second', 'sentence'],
#             ['yet', 'another', 'sentence'],
#             ['one', 'more', 'sentence'],
#             ['and', 'the', 'final', 'sentence']]
# # train model
# model_1 = Word2Vec(sentences, size=300, min_count=1)

# # fit a 2d PCA model to the vectors
# X = model_1[model_1.wv.vocab]
# pca = PCA(n_components=2)
# result = pca.fit_transform(X)
# # create a scatter plot of the projection
# pyplot.scatter(result[:, 0], result[:, 1])
# words = list(model_1.wv.vocab)
# for i, word in enumerate(words):
#     pyplot.annotate(word, xy=(result[i, 0], result[i, 1]))
# pyplot.show()

In [ ]:
# from gensim.models import KeyedVectors
# # Load vectors directly from the file
# model = KeyedVectors.load_word2vec_format('data/GoogleGoogleNews-vectors-negative300.bin', binary=True)
# # Access vectors for specific words with a keyed lookup:
# vector = model['easy']
# # see the shape of the vector (300,)
# vector.shape


In [14]:
from tensorflow.keras.preprocessing.text import one_hot

In [15]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [16]:

### Vocabulary size
voc_size=10000

In [17]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[1449, 2379, 1909, 4464], [1449, 2379, 1909, 7402], [1449, 2008, 1909, 5724], [98, 5291, 2993, 8402, 9663], [98, 5291, 2993, 8402, 2202], [8711, 1449, 7922, 1909, 9126], [5609, 6677, 1968, 8402]]


In [18]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [19]:
import numpy as np

In [21]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1449 2379 1909 4464]
 [   0    0    0    0 1449 2379 1909 7402]
 [   0    0    0    0 1449 2008 1909 5724]
 [   0    0    0   98 5291 2993 8402 9663]
 [   0    0    0   98 5291 2993 8402 2202]
 [   0    0    0 8711 1449 7922 1909 9126]
 [   0    0    0    0 5609 6677 1968 8402]]


In [22]:
dim=10


In [23]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [24]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [25]:
print(model.predict(embedded_docs))

[[[ 4.16458882e-02  2.94906832e-02 -1.59270391e-02  9.73240286e-03
   -5.89147955e-03 -4.27700058e-02 -3.50826383e-02  4.82779406e-02
    3.17746736e-02 -4.59256880e-02]
  [ 4.16458882e-02  2.94906832e-02 -1.59270391e-02  9.73240286e-03
   -5.89147955e-03 -4.27700058e-02 -3.50826383e-02  4.82779406e-02
    3.17746736e-02 -4.59256880e-02]
  [ 4.16458882e-02  2.94906832e-02 -1.59270391e-02  9.73240286e-03
   -5.89147955e-03 -4.27700058e-02 -3.50826383e-02  4.82779406e-02
    3.17746736e-02 -4.59256880e-02]
  [ 4.16458882e-02  2.94906832e-02 -1.59270391e-02  9.73240286e-03
   -5.89147955e-03 -4.27700058e-02 -3.50826383e-02  4.82779406e-02
    3.17746736e-02 -4.59256880e-02]
  [ 4.32032086e-02 -2.33460311e-02  5.86249679e-03  1.35448910e-02
   -1.07541308e-02  1.80083551e-02  4.56459820e-05  4.18718196e-02
    1.81938335e-03  4.48805131e-02]
  [ 4.42247130e-02  2.52726786e-02  3.81636955e-02 -8.50348547e-03
    4.20886017e-02 -1.65400282e-02 -4.14192788e-02  2.37041973e-02
   -1.93905588e-

In [26]:
embedded_docs[0]

array([   0,    0,    0,    0, 1449, 2379, 1909, 4464], dtype=int32)

In [27]:
print(model.predict(embedded_docs)[0])


[[ 4.1645888e-02  2.9490683e-02 -1.5927039e-02  9.7324029e-03
  -5.8914796e-03 -4.2770006e-02 -3.5082638e-02  4.8277941e-02
   3.1774674e-02 -4.5925688e-02]
 [ 4.1645888e-02  2.9490683e-02 -1.5927039e-02  9.7324029e-03
  -5.8914796e-03 -4.2770006e-02 -3.5082638e-02  4.8277941e-02
   3.1774674e-02 -4.5925688e-02]
 [ 4.1645888e-02  2.9490683e-02 -1.5927039e-02  9.7324029e-03
  -5.8914796e-03 -4.2770006e-02 -3.5082638e-02  4.8277941e-02
   3.1774674e-02 -4.5925688e-02]
 [ 4.1645888e-02  2.9490683e-02 -1.5927039e-02  9.7324029e-03
  -5.8914796e-03 -4.2770006e-02 -3.5082638e-02  4.8277941e-02
   3.1774674e-02 -4.5925688e-02]
 [ 4.3203209e-02 -2.3346031e-02  5.8624968e-03  1.3544891e-02
  -1.0754131e-02  1.8008355e-02  4.5645982e-05  4.1871820e-02
   1.8193834e-03  4.4880513e-02]
 [ 4.4224713e-02  2.5272679e-02  3.8163695e-02 -8.5034855e-03
   4.2088602e-02 -1.6540028e-02 -4.1419279e-02  2.3704197e-02
  -1.9390559e-02 -3.0658806e-02]
 [-3.5646059e-02 -1.5258454e-02  2.9052284e-02 -1.3695646e